//
//  File.swift
//  
//
//  Created by Super Grover on 2024-11-25.
//

import Foundation



public struct kFSPMockData {
    
    /// For add test Recipe Favorite via the Demo Mode "Add Test Foods" UISwitch button:
    public static let fspRecipeFavorites: [FSPSingleRecipe] = [
        FSPSingleRecipe(cooking_time_min: "5",
                        directions: Directions(direction: [
                            Direction(direction_description: "Spread tablespoon of peanut butter onto the middle of tortilla.",
                                      direction_number: "1"),
                            Direction(direction_description: "Put about a third of a cup of the apples in the middle of the tortilla. (Add cinnamon and sugar to taste if you so choose.)",
                                      direction_number: "2"),
                            Direction(direction_description: "Fold the tortilla in and around the apples. Place in the oven if you want to eat it warm, or eat as is.",
                                      direction_number: "3"),
                            Direction(direction_description: "Note: can be eaten plain, topped with sugar and fruit, or with sugared cream cheese (use reduced fat cream cheese and sugar to taste).",
                                      direction_number: "4"),
                        ]),
                        ingredients: Ingredients(ingredient: [
                            Ingredient(food_id: "25054",
                                       food_name: "Organic Peanut Butter",
                                       ingredient_description: "2 tbsp peanut butter",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/smuckers/organic-peanut-butter?portionid=0&portionamount=0.500")!,
                                       measurement_description: "serving",
                                       number_of_units: "0.500",
                                       serving_id: "0"),
                            Ingredient(food_id: "88613",
                                       food_name: "Life Balance Whole Wheat Tortillas Plus! (Medium)",
                                       ingredient_description: "1 whole wheat tortilla",
                                       ingredient_url:URL(string: "https://www.fatsecret.com/calories-nutrition/mission/life-balance-whole-wheat-tortillas-plus-(medium)?portionid=0&portionamount=1.000")!,
                                       measurement_description: "serving",
                                       number_of_units: "1.000",
                                       serving_id: "0"),
                            Ingredient(food_id: "75716",
                                       food_name: "Fried Apples",
                                       ingredient_description: "1/2 cup fried apples",
                                       ingredient_url: URL(string: "https://www.fatsecret.com/calories-nutrition/lucks/fried-apples?portionid=0&portionamount=1.000")!,
                                       measurement_description: "serving",
                                       number_of_units: "1.000",
                                       serving_id: "0")
                        ]),
                        number_of_servings: "1",
                        preparation_time_min: "5",
                        rating: "3",
                        recipe_categories: RecipeCategories(recipe_category: [
                            RecipeCategory(recipe_category_name: "Dessert",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/dessert/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Pie Dessert",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/dessert/pie/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Snack",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/snack/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Sweet Snack",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/snack/sweet/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "High Fiber",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/nutrition/high-fiber/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Low Cholesterol",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/nutrition/low-cholesterol/Default.aspx")!),
                        ]),
                        recipe_description: "Surprisingly delicious apple pie filling and peanut butter wrapped up in a whole wheat tortilla.",
                        recipe_id: "187769",
                        recipe_images: RecipeImage(recipe_image: [URL(string: "https://m.ftscrt.com/static/recipe/57852fa0-eb3a-4abe-8f0f-94016290842b.jpg")!]),
                        recipe_name: "Apple Pie Pockets (Test)",
                        recipe_types: RecipeTypes(recipe_type: ["Dessert",
                                                                "Snack"]),
                        recipe_url: URL(string: "https://www.fatsecret.com/recipes/apple-pie-pockets/Default.aspx"),
                        serving_sizes: FSPRecipeServing(serving: FSPRecipeServingInfo(calcium: 0.0,
                                                                                      calories: 345.0,
                                                                                      carbohydrate: 56.0,
                                                                                      cholesterol: 0.0,
                                                                                      fat: 10.5,
                                                                                      fiber: 7.0,
                                                                                      iron: 0.0,
                                                                                      monounsaturated_fat: 0.0,
                                                                                      polyunsaturated_fat: 1.50,
                                                                                      potassium: 0.0,
                                                                                      protein: 8.0,
                                                                                      saturated_fat: 2.25,
                                                                                      serving_size: 1,
                                                                                      sodium: 325.0,
                                                                                      sugar: 22.50,
                                                                                      trans_fat: 0.0,
                                                                                      vitamin_c: 0.0))
                       ),
        FSPSingleRecipe(cooking_time_min: "45",
                        directions: Directions(direction: [
                            Direction(direction_description: "To make the pastry, blend flour and salt in a large bowl.",
                                      direction_number: "1"),
                            Direction(direction_description: "Add margarine and cut through with a knife to blend.",
                                      direction_number: "2"),
                            Direction(direction_description: "Add water and vinegar and knead to form dough.",
                                      direction_number: "3"),
                            Direction(direction_description: "Divide dough in half and roll out each half until very thin.",
                                      direction_number: "4"),
                            Direction(direction_description: "To make the filling mix all ingredients together.",
                                      direction_number: "5"),
                            Direction(direction_description: "Preheat oven to 350 °F (175 °C). Cover each rectangle of dough with filling, roll up.",
                                      direction_number: "6"),
                            Direction(direction_description: "Place on baking sheet with dough joint facing down.",
                                      direction_number: "7"),
                            Direction(direction_description: "Brush with glaze and bake 45 minutes until golden.",
                                      direction_number: "8")
                        ]),
                        ingredients: Ingredients(ingredient: [
                            Ingredient(food_id: "33792",
                                       food_name: "Egg (Whole)",
                                       ingredient_description: "1 large egg, with 1 tbsp water, lightly beaten for glaze",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/egg-(whole)?portionid=29441&portionamount=1.000")!,
                                       measurement_description: "large",
                                       number_of_units: "1.000",
                                       serving_id: "29441"),
                            Ingredient(food_id: "33872",
                                       food_name: "Cinnamon",
                                       ingredient_description: "1/4 tsp cinnamon",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/cinnamon?portionid=29575&portionamount=0.250")!,
                                       measurement_description: "tsp",
                                       number_of_units: "0.250",
                                       serving_id: "29575"),
                            Ingredient(food_id: "33908",
                                       food_name: "Salt",
                                       ingredient_description: "1/4 tsp salt",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/salt?portionid=29653&portionamount=0.250")!,
                                       measurement_description: "tsp",
                                       number_of_units: "0.250",
                                       serving_id: "29653"),
                            Ingredient(food_id: "33914",
                                       food_name: "Vinegar",
                                       ingredient_description: "1 tbsp vinegar",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/vinegar?portionid=29667&portionamount=1.000")!,
                                       measurement_description: "tbsp",
                                       number_of_units: "1.000",
                                       serving_id: "29667"),
                            Ingredient(food_id: "35718",
                                       food_name: "Apples",
                                       ingredient_description: "4 medium tart apples, peeled and sliced",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/apples?portionid=32915&portionamount=4.000")!,
                                       measurement_description: "medium (2-3/4\" dia) (approx 3 per lb)",
                                       number_of_units: "4.000",
                                       serving_id: "32915"),
                            Ingredient(food_id: "34340",
                                       food_name: "Margarine (Approx. 48% Fat, Tub)",
                                       ingredient_description: "1 oz margarine",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/margarine-(approx-48%25-fat-tub)?portionid=42313&portionamount=1.000")!,
                                       measurement_description: "oz",
                                       number_of_units: "1.000",
                                       serving_id: "42313"),
                            Ingredient(food_id: "35962",
                                       food_name: "Raisins (Seedless)",
                                       ingredient_description: "1/4 cup sultanas or raisins",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/raisins-(seedless)?portionid=33374&portionamount=0.250")!,
                                       measurement_description: "cup (not packed)",
                                       number_of_units: "0.250",
                                       serving_id: "33374"),
                            Ingredient(food_id: "37092",
                                       food_name: "Dried Black Walnuts",
                                       ingredient_description: "1/4 cup chopped walnuts",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/dried-black-walnuts?portionid=35401&portionamount=0.250")!,
                                       measurement_description: "cup, chopped",
                                       number_of_units: "0.250",
                                       serving_id: "35401"),
                            Ingredient(food_id: "37922",
                                       food_name: "Water",
                                       ingredient_description: "1/3 cup water",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/water?portionid=36941&portionamount=0.330")!,
                                       measurement_description: "cup (8 fl oz)",
                                       number_of_units: "0.330",
                                       serving_id: "36941"),
                            Ingredient(food_id: "39559",
                                       food_name: "Granulated Sugar",
                                       ingredient_description: "1/2 cup sugar",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/granulated-sugar?portionid=40105&portionamount=0.500")!,
                                       measurement_description: "cup",
                                       number_of_units: "0.500",
                                       serving_id: "40105"),
                            Ingredient(food_id: "39830",
                                       food_name: "White Wheat Flour (All Purpose)",
                                       ingredient_description: "2 1/2 cups flour, sifted",
                                       ingredient_url: URL(string:"https://www.fatsecret.com/calories-nutrition/usda/white-wheat-flour-(all-purpose)?portionid=40447&portionamount=2.500")!,
                                       measurement_description: "cup",
                                       number_of_units: "2.500",
                                       serving_id: "40447")
                        ]),
                        number_of_servings: "8",
                        preparation_time_min: "15",
                        rating: "1",
                        recipe_categories: RecipeCategories(recipe_category: [
                            RecipeCategory(recipe_category_name: "Fruit",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/ingredients/fruit/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Apple",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/ingredients/fruit/apple/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Bakery & Baked Products",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/bakery-and-baked-products/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Pastry",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/bakery-and-baked-products/pastry/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Dessert",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/dessert/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Fruit Dessert",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/dessert/fruit/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Specialty Dessert",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/dessert/specialty/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Snack",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/snack/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Sweet Snack",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/meal/snack/sweet/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "Low Calorie",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/nutrition/low-calorie/Default.aspx")!),
                            RecipeCategory(recipe_category_name: "200-300 Calorie",
                                           recipe_category_url: URL(string:"https://www.fatsecret.com/recipes/collections/nutrition/low-calorie/200-300-calorie/Default.aspx")!)
                        ]),
                        recipe_description: "Homemade pastry and delicous fillings - what could be better.",
                        recipe_id: "69",
                        recipe_images: RecipeImage(recipe_image: [URL(string: "https://m.ftscrt.com/static/recipe/e7bd4c1a-8bdf-4351-b71d-02abcf42a061.jpg")!]),
                        recipe_name: "Apple Strudel (Test)",
                        recipe_types: RecipeTypes(recipe_type: ["Baked",
                                                                "Dessert",
                                                                "Snack"]),
                        recipe_url: URL(string: "https://www.fatsecret.com/recipes/apple-strudel/Default.aspx"),
                        serving_sizes: FSPRecipeServing(serving: FSPRecipeServingInfo(calcium: 2.0,
                                                                                      calories: 289.0,
                                                                                      carbohydrate: 55.95,
                                                                                      cholesterol: 26.0,
                                                                                      fat: 5.13,
                                                                                      fiber: 3.2,
                                                                                      iron: 5.0,
                                                                                      monounsaturated_fat: 1.448,
                                                                                      polyunsaturated_fat: 2.371,
                                                                                      potassium: 180.0,
                                                                                      protein: 6.09,
                                                                                      saturated_fat: 0.72,
                                                                                      serving_size: 1,
                                                                                      sodium: 107.0,
                                                                                      sugar: 22.54,
                                                                                      trans_fat: 0.156,
                                                                                      vitamin_c: 4.0))
                       ),
    ]
    
    
    
}
